title: ChoacuryOS Documentation
description: The documentation for ChoacuryOS
theme: just-the-docs

color_scheme: dark

url: https://teamchoacury.github.io/docs/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
